backend:
  name: test-repo
  branch: main
media_folder: public/media/uploads
public_folder: media/uploads
collections:
  - name: "pages"
    label: "pages"
    files:
      - name: "home"
        label: "home"
        file: "content/home.md"
        fields:
          - name: "headbar"
            widget: "object"
            fields:
              - name: "title-left"
                label: "title-left"
                widget: "string"
              - name: "title-right"
                label: "title-right"
                widget: "string"
              - name: "title-icon"
                label: "title-icon"
                widget: "image"
                choose_url: false
              - name: "title-decorator-ratio"
                label: "title-decorator-ratio"
                widget: "number"
                value_type: "float"
                min: 0.0
                max: 1.0
                step: 0.05
                default: 0.0
          - name: "navigation"
            widget: "object"
            fields:
              - name: "about"
                label: "about"
                widget: "object"
                fields:
                  - name: "title"
                    widget: "string"
              - name: "projects"
                label: "projects"
                widget: "object"
                fields:
                  - name: "title"
                    widget: "string"
              - name: "contact"
                label: "contact"
                widget: "object"
                fields:
                  - name: "title"
                    widget: "string"